import { chromium } from 'playwright';
const base = process.argv[2] ?? 'http://localhost:8080';
const b = await chromium.launch({ args: ['--no-sandbox', '--mute-audio'] });
const ctx = await b.newContext({ viewport: { width: 420, height: 900 }, deviceScaleFactor: 2 });
const host = await ctx.newPage();
await host.goto(`${base}/host`); await host.waitForTimeout(800);
await host.screenshot({ path: 'docs/shot-host-start.png' });
await host.fill('input[type=text]', 'Karim’s Music');
await host.click('[data-testid=create-session]');
await host.waitForSelector('[data-testid=speaker-count]');
await host.setInputFiles('[data-testid=file]', '/tmp/tone.wav');
await host.waitForFunction(() => document.querySelectorAll('[data-testid=playlist] .list-item').length > 0);
const sctx = await b.newContext({ viewport: { width: 420, height: 900 }, deviceScaleFactor: 2 });
const spk = await sctx.newPage();
await spk.goto(`${base}/speaker`);
await spk.waitForSelector('[data-testid=connect-host], [data-testid=enable-speaker]');
const cb = spk.locator('[data-testid=connect-host]'); if (await cb.count()) await cb.first().click();
await spk.click('[data-testid=enable-speaker]');
await host.click('[data-testid=play]');
await host.waitForTimeout(3000);
await host.screenshot({ path: 'docs/shot-host-live.png', fullPage: true });
await spk.screenshot({ path: 'docs/shot-speaker.png' });
const home = await ctx.newPage(); await home.goto(base); await home.waitForTimeout(1200);
await home.screenshot({ path: 'docs/shot-home.png', fullPage: true });
await b.close();
console.log('screenshots written to docs/');
